# Generated by Django 5.2 on 2025-04-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Nazwa użytkownika')),
                ('password', models.CharField(max_length=255, unique=True, verbose_name='Hasło')),
            ],
            options={
                'verbose_name': 'Użytkownik',
                'verbose_name_plural': 'Użytkownicy',
                'db_table': 'users',
            },
        ),
    ]
