version: '3.8'

services:
  db:
    image: mysql:8.4.1
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scrapper
    volumes:
      - db:/var/lib/mysql

  app:
    build: Docker/Python
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    expose:
      - '${REDIS_PORT}'
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}"
    volumes:
      - redis_data:/data

  celery:
    build: Docker/Python
    command: celery -A tenders_service worker --beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

volumes:
  db:
    driver: local
  redis_data:
    driver: local
