# Generated by Django 5.2.3 on 2025-06-21 21:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowTender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_uuid', models.UUIDField(verbose_name='UUID przetargu')),
                ('tender_type', models.CharField(choices=[('private', 'Prywatny'), ('public', 'Publiczny')], max_length=10, verbose_name='Typ przetargu')),
                ('followed_at', models.DateTimeField(auto_now_add=True, verbose_name='Data obserwowania')),
            ],
            options={
                'verbose_name': 'Obserwacja przetargu',
                'verbose_name_plural': 'Obserwacje przetargów',
                'db_table': 'follow_tender',
                'ordering': ['-followed_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivateTender',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('title', models.CharField(max_length=255, verbose_name='Tytuł')),
                ('description', models.TextField(verbose_name='Opis przetargu')),
                ('company_name', models.CharField(max_length=255, verbose_name='Nazwa firmy')),
                ('city', models.CharField(max_length=100, verbose_name='Miasto')),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('publication_date', models.DateField(verbose_name='Data publikacji')),
                ('submission_deadline', models.DateField(verbose_name='Termin składania ofert')),
                ('details_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Link do szczegółów')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
            ],
            options={
                'verbose_name': 'Przetarg prywatny',
                'verbose_name_plural': 'Przetargi prywatne',
                'db_table': 'private_tenders',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='PublicTender',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('tender_id', models.CharField(max_length=100, unique=True, verbose_name='Identyfikator przetargu')),
                ('announcement_number', models.CharField(max_length=50, verbose_name='Numer ogłoszenia')),
                ('announcement_type', models.CharField(max_length=50, verbose_name='Typ ogłoszenia')),
                ('order_name', models.TextField(verbose_name='Nazwa lub opis zamówienia')),
                ('contracting_authority', models.TextField(verbose_name='Zamawiający')),
                ('description', models.TextField(verbose_name='Opis')),
                ('authority_city', models.CharField(max_length=100, verbose_name='Miasto zamawiającego')),
                ('authority_region', models.CharField(max_length=50, verbose_name='Region zamawiającego')),
                ('publication_date', models.DateField(verbose_name='Data publikacji')),
                ('submission_deadline', models.DateField(blank=True, null=True, verbose_name='Termin składania ofert')),
                ('details_url', models.URLField(max_length=255, verbose_name='URL ze szczegółami')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data ostatniej aktualizacji')),
                ('client_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Typ klienta')),
                ('order_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Typ zamówienia')),
                ('tender_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Typ przetargu')),
                ('notice_type_ted', models.CharField(blank=True, max_length=50, null=True, verbose_name='Typ ogłoszenia TED')),
                ('notice_type_display_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Wyświetlana nazwa typu ogłoszenia')),
                ('bzp_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numer BZP')),
                ('is_tender_amount_below_eu', models.BooleanField(blank=True, null=True, verbose_name='Czy kwota przetargu poniżej progu UE')),
                ('cpv_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kod CPV')),
                ('procedure_result', models.CharField(blank=True, max_length=100, null=True, verbose_name='Wynik procedury')),
                ('authority_country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kraj zamawiającego')),
                ('authority_national_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Identyfikator krajowy zamawiającego')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID użytkownika')),
                ('organization_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID organizacji')),
                ('mo_identifier', models.CharField(blank=True, max_length=100, null=True, verbose_name='Identyfikator MO')),
                ('is_manually_linked_with_tender', models.BooleanField(blank=True, null=True, verbose_name='Czy ręcznie powiązany z przetargiem')),
                ('html_body', models.TextField(blank=True, null=True, verbose_name='Treść HTML')),
                ('contractors', models.JSONField(blank=True, null=True, verbose_name='Wykonawcy')),
                ('bzp_tender_plan_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numer planu przetargu BZP')),
                ('base_notice_mo_identifier', models.CharField(blank=True, max_length=100, null=True, verbose_name='Identyfikator MO ogłoszenia bazowego')),
                ('technical_notice_mo_identifier', models.CharField(blank=True, max_length=100, null=True, verbose_name='Identyfikator MO ogłoszenia technicznego')),
                ('outdated', models.BooleanField(blank=True, null=True, verbose_name='Czy nieaktualny')),
                ('object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID obiektu')),
                ('pdf_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL do PDF')),
            ],
            options={
                'verbose_name': 'Tender',
                'verbose_name_plural': 'Tenders',
                'db_table': 'tenders',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='TenderNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_uuid', models.UUIDField(verbose_name='UUID przetargu')),
                ('tender_type', models.CharField(choices=[('private', 'Prywatny'), ('public', 'Publiczny')], max_length=10, verbose_name='Typ przetargu')),
                ('note', models.TextField(verbose_name='Notatka')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
            ],
            options={
                'verbose_name': 'Notatka do przetargu',
                'verbose_name_plural': 'Notatki do przetargów',
                'db_table': 'tender_notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
