# Generated by Django 5.2 on 2025-04-09 23:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateTender',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tender_id', models.CharField(max_length=50, verbose_name='Identyfikator przetargu')),
                ('title', models.CharField(max_length=255, verbose_name='Tytuł')),
                ('description', models.TextField(verbose_name='Opis przetargu')),
                ('company_name', models.CharField(max_length=255, verbose_name='Nazwa firmy')),
                ('city', models.CharField(max_length=100, verbose_name='Miasto')),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('publication_date', models.DateField(verbose_name='Data publikacji')),
                ('submission_deadline', models.DateField(verbose_name='Termin składania ofert')),
                ('details_url', models.URLField(max_length=255, verbose_name='Link do szczegółów')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('user_hash_key', models.CharField(max_length=255, verbose_name='Klucz użytkownika')),
            ],
            options={
                'verbose_name': 'Przetarg prywatny',
                'verbose_name_plural': 'Przetargi prywatne',
                'db_table': 'private_tenders',
            },
        ),
        migrations.CreateModel(
            name='PublicTender',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tender_id', models.CharField(max_length=50, unique=True, verbose_name='Identyfikator przetargu')),
                ('announcement_number', models.CharField(max_length=50, verbose_name='Numer ogłoszenia')),
                ('announcement_type', models.CharField(max_length=50, verbose_name='Typ ogłoszenia')),
                ('order_name', models.TextField(verbose_name='Nazwa lub opis zamówienia')),
                ('contracting_authority', models.TextField(verbose_name='Zamawiający')),
                ('description', models.TextField(verbose_name='Opis')),
                ('authority_city', models.CharField(max_length=100, verbose_name='Miasto zamawiającego')),
                ('authority_region', models.CharField(max_length=50, verbose_name='Region zamawiającego')),
                ('publication_date', models.DateField(verbose_name='Data publikacji')),
                ('submission_deadline', models.DateField(verbose_name='Termin składania ofert')),
                ('details_url', models.URLField(max_length=255, verbose_name='URL ze szczegółami')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data ostatniej aktualizacji')),
            ],
            options={
                'verbose_name': 'Tender',
                'verbose_name_plural': 'Tenders',
                'db_table': 'tenders',
            },
        ),
        migrations.CreateModel(
            name='TenderNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_uuid', models.UUIDField(verbose_name='UUID przetargu')),
                ('tender_type', models.CharField(choices=[('private', 'Prywatny'), ('public', 'Publiczny')], max_length=10, verbose_name='Typ przetargu')),
                ('user_hash_key', models.CharField(max_length=255, verbose_name='Klucz użytkownika')),
                ('note', models.TextField(verbose_name='Notatka')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
            ],
            options={
                'verbose_name': 'Notatka do przetargu',
                'verbose_name_plural': 'Notatki do przetargów',
                'db_table': 'tender_notes',
            },
        ),
        migrations.CreateModel(
            name='FollowPublicTender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_hash_key', models.CharField(max_length=255, verbose_name='Klucz użytkownika')),
                ('followed_at', models.DateTimeField(auto_now_add=True, verbose_name='Data obserwowania')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.publictender', verbose_name='Przetarg')),
            ],
            options={
                'verbose_name': 'Obserwacja przetargu',
                'verbose_name_plural': 'Obserwacje przetargów',
                'db_table': 'follow_tender',
            },
        ),
    ]
