# Generated by Django 5.2.3 on 2025-06-21 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='privatetender',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tenders', to=settings.AUTH_USER_MODEL, verbose_name='Właściciel'),
        ),
        migrations.AddField(
            model_name='privatetender',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_tenders', to=settings.AUTH_USER_MODEL, verbose_name='Udostępniono dla'),
        ),
        migrations.AddField(
            model_name='tendernote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_notes', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
        migrations.AddField(
            model_name='followtender',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_follows', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
    ]
