# Generated by Django 5.2.3 on 2025-06-21 23:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_alter_publictender_cpv_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='followpublictender',
            name='tender_type',
            field=models.CharField(choices=[('private', 'Prywatny'), ('public', 'Publiczny')], max_length=10, verbose_name='Typ przetargu'),
            preserve_default=False,
        ),
    ]
